# ==========================
# Configurație Scalping Bot
# ==========================

general:
  # Lista de simboluri Forex pe care se va tranzacționa
  symbols_forex:
    - GBPUSD
    - USDCHF
    - USDCAD
    - NZDUSD
    - EURGBP
    - EURCAD
    - GBPAUD
    - AUDJPY
    - NZDCAD
    - CHFJPY
    - EURUSD

  # Ținta de profit zilnică totală pentru toate simbolurile combinate.
  daily_profit: 750.0
  daily_loss: -250.0

  # Volum fix per tranzacție (dacă vrei să folosești fix, ignoră risk manager)
  fixed_lot_size: 0.01

  # Parametrii de risk management
  risk_per_trade: 0.02        # 2% risc per tranzacție
  max_position_lot: 0.3       # Limită lot maxim per poziție
  min_free_margin_ratio: 0.6  # Marjă liberă minimă 60%

  # Trailing stop global (activat la acest prag de profit)
  trailing_profit_threshold: 15.0

  # Thread monitoring configuration
  thread_monitor_logging: true

# ==========================
# Configurația strategiilor
# ==========================
strategies:
  pivot:
    enabled: true
    timeframe: M1            # Timeframe pe care rulează strategia
    atr_multiplier: 2.5      # Multiplicator ATR pentru calcul SL
    pivot_levels: [S1, R1]   # Niveluri pivot pe care să intre
    atr_period: 14           # ATR pentru SL

  moving_average_ribbon:
    enabled: false
    timeframe: M5            # Rulează pe M5
    sma_periods: [5, 8, 13]  # Perioadele SMA folosite pentru semnale
    atr_period: 14           # ATR pentru calcul SL/TP
    tp_atr_multiplier: 1.5   # Multiplicator ATR pentru TP
    sl_atr_multiplier: 2.5   # Multiplicator ATR pentru SL

  momentum_scalping:
    enabled: false
    timeframe: M1            # Rulează pe M1 (momentum rapid)
    rsi_period: 14           # RSI pentru detectarea momentum-ului
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    atr_period: 14           # ATR pentru SL/TP
    tp_atr_multiplier: 1.5   # Multiplicator ATR pentru TP
    sl_atr_multiplier: 2.0   # Multiplicator ATR pentru SL

  ema_crossover:
    enabled: false

  ema_rsi_filter:
    enabled: false

  linear_regression:
    enabled: false

  rmi_supertrend:
    enabled: false
